#![allow(
    missing_docs,
    clippy::arithmetic_side_effects,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::missing_const_for_fn,
    clippy::panic,
    clippy::unwrap_used
)]
// SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
//
// SPDX-License-Identifier: Apache-2.0

//! Executes static interop vectors generated by panva/jose.
//!
//! These are independent positive fixtures, not a replacement for the local
//! negative corpus. Node is only used by the optional maintenance generator in
//! `tools/panva-goldens`; normal Rust tests consume this checked-in JSON.
//! The suite runs through the native Rust lane and intentionally covers only a
//! small set of high-value positive interop cases.

use serde::Deserialize;
use serde_json::Value;

use reallyme_jose::jwe::{
    decrypt_compact_jwe_json, CompactJwePolicy, CompactJweProtectedHeader,
    JweContentEncryptionKeyResolver, JweError, P256EcdhEsJweKeyResolver,
};
use reallyme_jose::jws::suites::eddsa::verify_eddsa_jws;
use reallyme_jose::jws::suites::es256::verify_es256_jws;
use reallyme_jose::jwt::{decode_verify_jwt_signature_only, JwtError};
use reallyme_jose::Jwk;

#[derive(Debug, Deserialize)]
struct PanvaSuite {
    source: String,
    cases: Vec<PanvaCase>,
}

#[derive(Debug, Deserialize)]
struct PanvaCase {
    id: String,
    source: String,
    format: String,
    alg: String,
    enc: Option<String>,
    compact: String,
    payload_utf8: Option<String>,
    public_key_hex: Option<String>,
    verification_jwk: Option<Value>,
    expected_claims_json: Option<Value>,
    protected_header: Option<Value>,
    expected_plaintext_json: Option<Value>,
    recipient_private_key_hex: Option<String>,
    derived_cek_hex: Option<String>,
}

#[test]
fn panva_jose_vectors_interoperate() -> Result<(), PanvaTestError> {
    let suite: PanvaSuite =
        serde_json::from_str(include_str!("../../conformance/vectors/panva-jose.json"))?;
    assert_eq!(suite.source, "panva/jose@6.2.3");
    assert_eq!(suite.cases.len(), 4);

    for case in suite.cases {
        assert_eq!(case.source, suite.source, "{}", case.id);
        match case.format.as_str() {
            "jws-compact" => verify_panva_jws(&case)?,
            "jwt-compact" => verify_panva_jwt(&case)?,
            "jwe-compact" => decrypt_panva_jwe(&case)?,
            other => panic!("{}: unsupported panva vector format {other}", case.id),
        }
    }

    Ok(())
}

fn verify_panva_jws(case: &PanvaCase) -> Result<(), PanvaTestError> {
    let public_key = hex_to_bytes(required(
        case.public_key_hex.as_deref(),
        case,
        "public_key",
    )?)?;

    match case.alg.as_str() {
        "ES256" => verify_es256_jws(&case.compact, &public_key)?,
        "EdDSA" => verify_eddsa_jws(&case.compact, &public_key)?,
        other => panic!("{}: unsupported panva JWS alg {other}", case.id),
    }

    let payload = case
        .compact
        .split('.')
        .nth(1)
        .ok_or(PanvaTestError::InvalidCompact)?;
    let payload = reallyme_codec::base64url::base64url_to_bytes(payload)
        .map_err(|_| PanvaTestError::InvalidBase64Url)?;
    let expected_payload = required(case.payload_utf8.as_deref(), case, "payload_utf8")?;
    assert_eq!(payload, expected_payload.as_bytes(), "{}", case.id);

    Ok(())
}

fn verify_panva_jwt(case: &PanvaCase) -> Result<(), PanvaTestError> {
    let public_key = hex_to_bytes(required(
        case.public_key_hex.as_deref(),
        case,
        "public_key",
    )?)?;
    let jwk: Jwk = serde_json::from_value(required_value(&case.verification_jwk, case, "jwk")?)?;
    let claims: Value = decode_verify_jwt_signature_only(&case.compact, &jwk, &public_key)?;

    assert_eq!(
        Some(&claims),
        case.expected_claims_json.as_ref(),
        "{}",
        case.id
    );

    Ok(())
}

fn decrypt_panva_jwe(case: &PanvaCase) -> Result<(), PanvaTestError> {
    assert_eq!(case.alg, "ECDH-ES", "{}", case.id);
    assert_eq!(case.enc.as_deref(), Some("A128GCM"), "{}", case.id);

    let private_key = hex_to_bytes(required(
        case.recipient_private_key_hex.as_deref(),
        case,
        "recipient_private_key_hex",
    )?)?;
    let plaintext: Value = decrypt_compact_jwe_json(
        &case.compact,
        &CompactJwePolicy::openid4vp_direct_post_jwt(),
        &P256EcdhEsJweKeyResolver::new(&private_key),
    )?;
    assert_eq!(
        Some(&plaintext),
        case.expected_plaintext_json.as_ref(),
        "{}",
        case.id
    );

    let header: CompactJweProtectedHeader = serde_json::from_value(required_value(
        &case.protected_header,
        case,
        "protected_header",
    )?)?;
    let resolved =
        P256EcdhEsJweKeyResolver::new(&private_key).resolve_content_encryption_key(&header, &[])?;
    assert_eq!(
        bytes_to_hex(&resolved),
        required(case.derived_cek_hex.as_deref(), case, "derived_cek_hex")?,
        "{}",
        case.id
    );

    Ok(())
}

fn required<'a>(
    value: Option<&'a str>,
    case: &PanvaCase,
    name: &str,
) -> Result<&'a str, PanvaTestError> {
    value.ok_or_else(|| PanvaTestError::MissingField {
        case_id: case.id.clone(),
        name: name.to_owned(),
    })
}

fn required_value(
    value: &Option<Value>,
    case: &PanvaCase,
    name: &str,
) -> Result<Value, PanvaTestError> {
    value.clone().ok_or_else(|| PanvaTestError::MissingField {
        case_id: case.id.clone(),
        name: name.to_owned(),
    })
}

fn hex_to_bytes(input: &str) -> Result<Vec<u8>, PanvaTestError> {
    if !input.len().is_multiple_of(2) {
        return Err(PanvaTestError::InvalidHex);
    }

    let mut out = Vec::with_capacity(input.len() / 2);
    for pair in input.as_bytes().chunks_exact(2) {
        let high = hex_nibble(pair[0])?;
        let low = hex_nibble(pair[1])?;
        out.push((high << 4) | low);
    }
    Ok(out)
}

fn hex_nibble(value: u8) -> Result<u8, PanvaTestError> {
    match value {
        b'0'..=b'9' => Ok(value - b'0'),
        b'a'..=b'f' => Ok(value - b'a' + 10),
        b'A'..=b'F' => Ok(value - b'A' + 10),
        _ => Err(PanvaTestError::InvalidHex),
    }
}

fn bytes_to_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(char::from(HEX[usize::from(byte >> 4)]));
        out.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    out
}

#[derive(Debug, thiserror::Error)]
enum PanvaTestError {
    #[error("invalid panva vector JSON")]
    Json(#[from] serde_json::Error),
    #[error("invalid panva vector hex")]
    InvalidHex,
    #[error("invalid panva vector compact serialization")]
    InvalidCompact,
    #[error("invalid panva vector base64url")]
    InvalidBase64Url,
    #[error("missing panva vector field {name} in {case_id}")]
    MissingField { case_id: String, name: String },
    #[error("JWS ES256 verification failed")]
    Es256(#[from] reallyme_jose::jws::suites::es256::JwsEs256Error),
    #[error("JWS EdDSA verification failed")]
    EdDsa(#[from] reallyme_jose::jws::suites::eddsa::JwsEddsaError),
    #[error("JWT verification failed")]
    Jwt(#[from] JwtError),
    #[error("JWE decrypt failed")]
    Jwe(#[from] JweError),
}
