// SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
//
// SPDX-License-Identifier: Apache-2.0

package me.really.jose

/** Stable Rust-owned JOSE failure branch. */
public enum class ReallyMeJoseErrorBranch {
    PRIMITIVE,
    PROVIDER,
    BACKEND,
}

/** Stable JOSE reason code. Entries intentionally carry no input or backend text. */
@Suppress("MagicNumber")
public enum class ReallyMeJoseErrorReason(public val code: Int) {
    JWS_INVALID_COMPACT(100), JWS_INPUT_TOO_LARGE(101), JWS_LENGTH_OVERFLOW(102),
    JWS_INVALID_PAYLOAD_UTF8(103), JWS_BAD_PAYLOAD_BASE64(104), JWS_BAD_HEADER_BASE64(120),
    JWS_BAD_HEADER_UTF8(121),
    JWS_HEADER_MISMATCH(122), JWS_BAD_SIGNATURE_BASE64(140), JWS_BAD_RAW_SIGNATURE(141),
    JWS_INVALID_SIGNATURE(142), JWS_SIGN_FAILED(160), JWS_BAD_DER_SIGNATURE(161),
    JWE_INVALID_COMPACT(200), JWE_INPUT_TOO_LARGE(201), JWE_INVALID_ENCODING(202),
    JWE_INVALID_HEADER(220), JWE_UNSUPPORTED_KEY_MANAGEMENT_ALGORITHM(221),
    JWE_UNSUPPORTED_CONTENT_ENCRYPTION_ALGORITHM(222), JWE_MISSING_REQUIRED_HEADER_PARAMETER(223),
    JWE_HEADER_POLICY_MISMATCH(224), JWE_KID_POLICY_MISMATCH(225), JWE_APU_POLICY_MISMATCH(226),
    JWE_APV_POLICY_MISMATCH(227), JWE_INVALID_ENCRYPTED_KEY(240),
    JWE_INVALID_CONTENT_ENCRYPTION_KEY(241), JWE_INVALID_CONTENT_CIPHER_INPUT(242),
    JWE_DECRYPT_FAILED(243), JWE_ENCRYPT_FAILED(244), JWE_INVALID_KEY_AGREEMENT_KEY(245),
    JWE_LENGTH_OVERFLOW(246), JWE_INVALID_SHARED_SECRET(247), JWE_INVALID_PAYLOAD_JSON(260),
    JWT_INVALID_COMPACT(300), JWT_INPUT_TOO_LARGE(301), JWT_BASE64URL_DECODE_FAILED(302),
    JWT_LENGTH_OVERFLOW(303), JWT_INVALID_HEADER(320), JWT_UNSUPPORTED_ALGORITHM(321),
    JWT_ALGORITHM_MISMATCH(322), JWT_MISSING_ALGORITHM(323), JWT_MISSING_PRIVATE_KEY(324),
    JWT_MISSING_PUBLIC_KEY(325), JWT_KID_POLICY_MISMATCH(326), JWT_PUBLIC_KEY_MISMATCH(327),
    JWT_INVALID_PUBLIC_KEY(328), JWT_INVALID_JWK(329), JWT_INVALID_SIGNATURE(340),
    JWT_CRYPTO_FAILED(341), JWT_INVALID_CLAIMS(360), JWT_SERIALIZATION_FAILED(361),
    JWT_MISSING_REQUIRED_TEMPORAL_CLAIM(380), JWT_INVALID_TEMPORAL_CLAIM_VALUE(381),
    JWT_EXPIRED(382), JWT_NOT_YET_VALID(383), JWT_ISSUED_AT_IN_FUTURE(384),
    JWT_INVALID_VERIFICATION_TIME(385), JWT_INVALID_VERIFICATION_POLICY(386),
    JWT_SIGNING_KEY_MISMATCH(387), JWT_MISSING_REQUIRED_REGISTERED_CLAIM(388),
    JWT_INVALID_REGISTERED_CLAIM_VALUE(389), JWT_AUDIENCE_MISMATCH(390),
    JWT_ISSUER_MISMATCH(391), JWT_SUBJECT_MISMATCH(392), COMMON_MALFORMED_PROTOBUF(700),
    COMMON_MALFORMED_JSON(701),
    COMMON_MISSING_OPERATION(702), COMMON_RESOURCE_LIMIT_EXCEEDED(703), PROVIDER_UNAVAILABLE(800),
    PROVIDER_UNSUPPORTED(801), PROVIDER_RANDOMNESS_UNAVAILABLE(802), BACKEND_INTERNAL(900),
    BACKEND_JSON_SERIALIZATION(901), BACKEND_KEY_DERIVATION_FAILED(902),
    ;

    internal companion object {
        private val byCode: Map<Int, ReallyMeJoseErrorReason> = entries.associateBy { it.code }

        fun fromCode(code: Int): ReallyMeJoseErrorReason? = byCode[code]
    }
}

/** Audit-safe JVM exceptions. No variant contains secrets, PII, paths, or backend text. */
public sealed class ReallyMeJoseException(message: String) : RuntimeException(message) {
    public class JoseFailure(
        public val branch: ReallyMeJoseErrorBranch,
        public val reason: ReallyMeJoseErrorReason,
    ) : ReallyMeJoseException("JOSE operation failed")

    public class InvalidInput : ReallyMeJoseException("invalid input")

    public class NativeProviderFailure : ReallyMeJoseException("native provider failure")

    public class MalformedProviderResponse : ReallyMeJoseException("malformed provider response")
}
